#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
===============================================================================
OSAF PROGRAM 31 — LONG-TERM PWP SPATIAL-CONNECTIVITY SENSITIVITY
===============================================================================

VERSION
    1.0.1

PURPOSE
    Quantify, over the complete daily observational record, how the SST
    threshold used to define the Pacific Warm Pool (PWP) affects its spatial
    connectivity and the robustness of its spherical centroid.

    Program 31 is the long-term extension of the connected-component diagnostic
    introduced in Program 30 v1.2.0.

SCIENTIFIC QUESTION
    Does the centroid calculated from ALL threshold-qualified PWP cells remain
    representative of the dominant connected warm-pool body through time?

    The analysis is performed independently for:

        28.0 °C
        28.5 °C
        29.0 °C

    For every available daily SST field, Program 31 compares:

        A) FULL THRESHOLD DOMAIN
           all valid Pacific-mask cells satisfying SST >= threshold;

        B) LARGEST CONNECTED COMPONENT
           the spatially connected threshold-defined component having the
           greatest spherical area.

PRIMARY DIAGNOSTICS
    For every date × threshold:

        - number of connected components;
        - total PWP area;
        - largest connected-component area;
        - fraction of total area in the largest component;
        - full-domain spherical centroid;
        - largest-component spherical centroid;
        - signed longitude difference;
        - latitude difference;
        - great-circle centroid separation.

CONNECTIVITY CONVENTION
    Eight-neighbour connectivity is used.

    Therefore, horizontal, vertical, and diagonal cell contacts are considered
    connected.

    Components are ranked by SPHERICAL AREA, not by grid-cell count.

IMPORTANT INTERPRETATION
    The number of components alone is NOT used as the principal coherence
    metric. Numerous very small isolated components can coexist with a highly
    coherent principal PWP.

    The primary coherence metric is:

        largest_component_area_fraction
            = largest_component_area / total_PWP_area

    The primary centroid-sensitivity metric is:

        centroid_distance_km
            = great-circle distance between the full-domain centroid and the
              centroid of the largest connected component.

AUTHORITATIVE UPSTREAM METHODOLOGY
    Program 31 does NOT redefine:

        - the Pacific Ocean mask;
        - the SST grid;
        - spherical grid-cell area;
        - spherical centroid mathematics;
        - SST-unit conversion;
        - longitude normalization;
        - daily OISST extraction.

    These operations are imported from:

        src_a/17_methodological_domain_figure.py

    Program 17 itself uses the fixed validated Pacific mask generated by the
    upstream mask workflow, including:

        src_a/01_build_mask.py
        src_a/02_test_mask.py
        src_a/04_interpolate_mask.py

AUTHORITATIVE CENTROID SERIES
    Program 05 calculates the project's threshold-specific PWP centroid series.

    Program 31 uses the Program-05 centroid CSVs to define the authoritative
    dates available for each threshold and to cross-check the full-domain
    centroid calculation.

    Expected locations:

        data/processed/28/centroid/pwp_centroid_series.csv
        data/processed/28.5/centroid/pwp_centroid_series.csv
        data/processed/29/centroid/pwp_centroid_series.csv

    with fallback support for:

        data/processed/<threshold>/pwp_centroid_series.csv

    IMPORTANT:
        Program 31 does NOT overwrite Program-05 centroid products.

INPUT DATA
    1. Daily NOAA OISST absolute SST NetCDF files beneath:

           data/raw/

       The exact file discovery, SST-variable identification, coordinate
       handling, SST-unit conversion, Pacific-mask alignment, and daily field
       loading are delegated to Program 17.

    2. Fixed Pacific mask and reference grids used by Program 17.

    3. Program-05 threshold-specific centroid series.

TEMPORAL DOMAIN
    Complete common daily record available simultaneously for:

        - Program-05 centroid dates at 28.0 °C;
        - Program-05 centroid dates at 28.5 °C;
        - Program-05 centroid dates at 29.0 °C.

    No temporal interpolation or climate-index upsampling is performed.

OUTPUT TABLES
    outputs/tables/threshold_comparison/pwp_long_term_connectivity/

        pwp_daily_connectivity_diagnostics.csv
            Long-format daily diagnostic table.

        pwp_connectivity_threshold_summary.csv
            Full-record threshold comparison.

        pwp_connectivity_annual_summary.csv
            Annual threshold-specific statistics.

        pwp_connectivity_extreme_days.csv
            Most spatially fragmented / centroid-sensitive days.

OUTPUT FIGURES
    outputs/figures/threshold_comparison/pwp_long_term_connectivity/

        pwp_largest_component_fraction_timeseries.png/pdf
        pwp_centroid_separation_timeseries.png/pdf
        pwp_connectivity_threshold_distributions.png/pdf
        pwp_connectivity_threshold_summary.png/pdf

CHECKPOINT / RESUME
    Because the analysis spans the complete daily record and requires daily
    spatial SST fields, Program 31 writes a checkpoint periodically:

        outputs/tables/threshold_comparison/pwp_long_term_connectivity/
            pwp_daily_connectivity_checkpoint.csv

    If interrupted, rerunning the program resumes from completed
    date × threshold combinations.

    The checkpoint is removed only after successful creation of the final daily
    table.

DEPENDENCIES
    Python 3.10+
    numpy
    pandas
    scipy
    matplotlib

    plus the dependencies already required by Program 17 (including xarray for
    OISST NetCDF access).

VERSION 1.0.1 CORRECTION
    Program 17's calculate_threshold_diagnostic() attaches event metadata and is
    valid only for its two representative dates. Program 31 v1.0.1 therefore
    uses Program 17's lower-level pwp_domain(), spherical_centroid(), and
    spherical_cell_areas_km2() methods directly for the complete daily record.

SCIENTIFIC ROLE IN THE PROJECT
    Program 31 is intended as the FINAL threshold-selection diagnostic before
    scientific freeze of the manuscript methodology.

    It is designed to determine whether 28.0 °C or 28.5 °C provides the most
    defensible primary PWP definition over the complete record, while evaluating
    29.0 °C as a warm-core sensitivity threshold.

    The program must not choose the threshold automatically. It produces the
    evidence required for the scientific decision.

===============================================================================
"""

from __future__ import annotations

import importlib.util
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import ndimage


# =============================================================================
# PROJECT DISCOVERY
# =============================================================================

THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parent.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

PROGRAM17_FILE = PROJECT_ROOT / "src_a" / "17_methodological_domain_figure.py"

if not PROGRAM17_FILE.is_file():
    raise FileNotFoundError(
        "Program 17 was not found:\n"
        f"{PROGRAM17_FILE}\n\n"
        "Place Program 31 in the project src/ directory."
    )


def load_program17():
    """Load Program 17 even though its filename begins with a number."""
    spec = importlib.util.spec_from_file_location(
        "pwp_program17_methodological_domain",
        PROGRAM17_FILE,
    )
    if spec is None or spec.loader is None:
        raise ImportError(f"Unable to load Program 17: {PROGRAM17_FILE}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


P17 = load_program17()


# =============================================================================
# CONFIGURATION
# =============================================================================

PROGRAM_NAME = "OSAF PROGRAM 31 — LONG-TERM PWP SPATIAL-CONNECTIVITY SENSITIVITY"
PROGRAM_VERSION = "1.0.1"

THRESHOLDS_C = (28.0, 28.5, 29.0)

CONNECTIVITY_STRUCTURE = np.ones((3, 3), dtype=np.uint8)
CONNECTIVITY_LABEL = "8-neighbour"

CHECKPOINT_EVERY_DATES = 25

# Thresholds used only for summary frequencies.
AREA_FRACTION_LEVELS = (0.90, 0.75, 0.50)
CENTROID_DISTANCE_LEVELS_KM = (250.0, 500.0, 1000.0)

TABLE_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "tables"
    / "threshold_comparison"
    / "pwp_long_term_connectivity"
)

FIGURE_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "figures"
    / "threshold_comparison"
    / "pwp_long_term_connectivity"
)

DAILY_CSV = TABLE_DIR / "pwp_daily_connectivity_diagnostics.csv"
CHECKPOINT_CSV = TABLE_DIR / "pwp_daily_connectivity_checkpoint.csv"
THRESHOLD_SUMMARY_CSV = TABLE_DIR / "pwp_connectivity_threshold_summary.csv"
ANNUAL_SUMMARY_CSV = TABLE_DIR / "pwp_connectivity_annual_summary.csv"
EXTREME_DAYS_CSV = TABLE_DIR / "pwp_connectivity_extreme_days.csv"

FIGURE_DPI = int(getattr(P17, "FIGURE_DPI", 300))
SAVE_BBOX = getattr(P17, "SAVE_BBOX", "tight")
SAVE_PAD_INCHES = float(getattr(P17, "SAVE_PAD_INCHES", 0.05))
SAVE_TRANSPARENT = bool(getattr(P17, "SAVE_TRANSPARENT", False))


# =============================================================================
# DATA STRUCTURE
# =============================================================================

@dataclass(frozen=True)
class DailyConnectivityDiagnostic:
    date: str
    year: int
    threshold_c: float
    connectivity: str

    component_count: int

    total_area_km2: float
    largest_component_area_km2: float
    largest_component_area_fraction: float

    full_centroid_lon_360: float
    full_centroid_lat: float

    largest_centroid_lon_360: float
    largest_centroid_lat: float

    delta_lon_deg: float
    delta_lat_deg: float
    centroid_distance_km: float


# =============================================================================
# PATH UTILITIES
# =============================================================================

def threshold_folder_name(threshold_c: float) -> str:
    if float(threshold_c).is_integer():
        return str(int(threshold_c))
    return f"{threshold_c:g}"


def centroid_csv_path(threshold_c: float) -> Path:
    """
    Resolve the authoritative Program-05 centroid series.

    Prefer central config path resolution when available.
    """
    config = getattr(P17, "project_config", None)

    if config is not None and hasattr(config, "get_threshold_paths"):
        try:
            paths = config.get_threshold_paths(float(threshold_c))
            centroid_group = getattr(paths, "centroid", None)
            if centroid_group is not None:
                candidate = (
                    Path(centroid_group.processed_dir)
                    / "pwp_centroid_series.csv"
                )
                if candidate.is_file():
                    return candidate
        except Exception:
            pass

    folder = threshold_folder_name(threshold_c)

    candidates = (
        PROJECT_ROOT / "data" / "processed" / folder
        / "centroid" / "pwp_centroid_series.csv",

        PROJECT_ROOT / "data" / "processed" / folder
        / "pwp_centroid_series.csv",
    )

    for candidate in candidates:
        if candidate.is_file():
            return candidate

    raise FileNotFoundError(
        f"Program-05 centroid series not found for {threshold_c:.1f} °C.\n"
        + "\n".join(str(path) for path in candidates)
    )


def identify_date_column(frame: pd.DataFrame) -> str:
    """Identify the date/time column in a centroid CSV."""
    preferred = (
        "date", "Date", "DATE",
        "time", "Time", "TIME",
        "datetime", "timestamp",
    )

    for name in preferred:
        if name in frame.columns:
            return name

    # Conservative fallback: first column that parses predominantly as dates.
    for name in frame.columns:
        parsed = pd.to_datetime(frame[name], errors="coerce")
        if parsed.notna().mean() >= 0.95:
            return name

    raise ValueError(
        "No date/time column could be identified in centroid series."
    )


def load_common_dates() -> pd.DatetimeIndex:
    """
    Load the intersection of authoritative Program-05 dates for all thresholds.
    """
    date_sets: list[set[pd.Timestamp]] = []

    print("## AUTHORITATIVE PROGRAM-05 DATE SERIES")
    print()

    for threshold in THRESHOLDS_C:
        path = centroid_csv_path(threshold)
        frame = pd.read_csv(path)
        date_column = identify_date_column(frame)

        dates = pd.DatetimeIndex(
            pd.to_datetime(frame[date_column], errors="coerce")
        ).normalize()
        dates = dates[~dates.isna()]

        unique_dates = set(pd.Timestamp(value) for value in dates.unique())
        date_sets.append(unique_dates)

        print(
            f"{threshold:4.1f} °C : {len(unique_dates):,} dates | {path}"
        )

    common = sorted(set.intersection(*date_sets))

    if not common:
        raise ValueError(
            "No common dates were found among the three centroid series."
        )

    common_dates = pd.DatetimeIndex(common)

    print()
    print(
        f"Common daily record : {len(common_dates):,} dates | "
        f"{common_dates.min():%Y-%m-%d} to {common_dates.max():%Y-%m-%d}"
    )
    print()

    return common_dates


# =============================================================================
# MATHEMATICAL UTILITIES
# =============================================================================

def signed_longitude_difference_deg(a_deg: float, b_deg: float) -> float:
    """Signed shortest angular difference a - b in [-180, 180)."""
    return float((a_deg - b_deg + 180.0) % 360.0 - 180.0)


def great_circle_distance_km(
    lon1_deg: float,
    lat1_deg: float,
    lon2_deg: float,
    lat2_deg: float,
) -> float:
    """Great-circle distance between two geographic positions."""
    radius_km = float(getattr(P17, "EARTH_RADIUS_KM", 6371.0088))

    lon1 = np.deg2rad(lon1_deg)
    lat1 = np.deg2rad(lat1_deg)
    lon2 = np.deg2rad(lon2_deg)
    lat2 = np.deg2rad(lat2_deg)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = (
        np.sin(dlat / 2.0) ** 2
        + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0) ** 2
    )

    angle = 2.0 * np.arcsin(np.sqrt(np.clip(a, 0.0, 1.0)))
    return float(radius_km * angle)


# =============================================================================
# CONNECTED-COMPONENT ANALYSIS
# =============================================================================

def largest_component_by_spherical_area(
    domain: np.ndarray,
    cell_areas_km2: np.ndarray,
) -> tuple[np.ndarray, int, float]:
    """
    Identify the connected component having the greatest spherical area.
    """
    if domain.shape != cell_areas_km2.shape:
        raise ValueError(
            "PWP domain and cell-area grid have inconsistent shapes."
        )

    labels, component_count = ndimage.label(
        domain.astype(bool),
        structure=CONNECTIVITY_STRUCTURE,
    )

    component_count = int(component_count)

    if component_count < 1:
        raise ValueError("No connected PWP component was identified.")

    ids = np.arange(1, component_count + 1, dtype=int)

    areas = np.asarray(
        ndimage.sum(
            input=cell_areas_km2,
            labels=labels,
            index=ids,
        ),
        dtype=np.float64,
    )

    largest_index = int(np.argmax(areas))
    largest_label = int(ids[largest_index])

    return (
        labels == largest_label,
        component_count,
        float(areas[largest_index]),
    )


def calculate_one(
    field,
    threshold_c: float,
    cell_areas_km2: np.ndarray,
) -> DailyConnectivityDiagnostic:
    """
    Calculate connectivity and centroid sensitivity for one day/threshold.

    Program 17's calculate_threshold_diagnostic() is deliberately NOT used
    here because that wrapper is restricted to Program 17's two representative
    dates through REPRESENTATIVE_DATES.

    Program 31 instead uses Program 17's validated low-level methods directly:
        - pwp_domain()
        - spherical_centroid()
        - spherical_cell_areas_km2()
    """

    full_domain = P17.pwp_domain(
        field,
        threshold_c,
    )

    if not np.any(full_domain):
        raise ValueError(
            f"No PWP cells on {field.date:%Y-%m-%d} "
            f"at {threshold_c:.1f} °C."
        )

    total_area_km2 = float(
        np.sum(
            cell_areas_km2[full_domain],
            dtype=np.float64,
        )
    )

    if not np.isfinite(total_area_km2) or total_area_km2 <= 0.0:
        raise ValueError(
            f"Invalid PWP area on {field.date:%Y-%m-%d} "
            f"at {threshold_c:.1f} °C: {total_area_km2}"
        )

    full_lon, full_lat = P17.spherical_centroid(
        latitude=field.latitude,
        longitude=field.longitude,
        weights=cell_areas_km2,
        selected=full_domain,
    )

    largest_domain, component_count, largest_area_km2 = (
        largest_component_by_spherical_area(
            domain=full_domain,
            cell_areas_km2=cell_areas_km2,
        )
    )

    largest_lon, largest_lat = P17.spherical_centroid(
        latitude=field.latitude,
        longitude=field.longitude,
        weights=cell_areas_km2,
        selected=largest_domain,
    )

    full_lon = float(full_lon)
    full_lat = float(full_lat)
    largest_lon = float(largest_lon)
    largest_lat = float(largest_lat)

    fraction = float(largest_area_km2 / total_area_km2)

    if fraction > 1.0 + 1.0e-10:
        raise ValueError(
            "Largest component area exceeds total PWP area on "
            f"{field.date:%Y-%m-%d} at {threshold_c:.1f} °C."
        )

    fraction = float(np.clip(fraction, 0.0, 1.0))

    delta_lon = signed_longitude_difference_deg(
        full_lon,
        largest_lon,
    )
    delta_lat = float(full_lat - largest_lat)

    distance = great_circle_distance_km(
        full_lon,
        full_lat,
        largest_lon,
        largest_lat,
    )

    return DailyConnectivityDiagnostic(
        date=f"{field.date:%Y-%m-%d}",
        year=int(field.date.year),
        threshold_c=float(threshold_c),
        connectivity=CONNECTIVITY_LABEL,
        component_count=component_count,
        total_area_km2=total_area_km2,
        largest_component_area_km2=float(largest_area_km2),
        largest_component_area_fraction=fraction,
        full_centroid_lon_360=full_lon,
        full_centroid_lat=full_lat,
        largest_centroid_lon_360=largest_lon,
        largest_centroid_lat=largest_lat,
        delta_lon_deg=delta_lon,
        delta_lat_deg=delta_lat,
        centroid_distance_km=distance,
    )


# =============================================================================
# CHECKPOINT / RESUME
# =============================================================================

DAILY_COLUMNS = [
    field.name
    for field in DailyConnectivityDiagnostic.__dataclass_fields__.values()
]


def load_checkpoint() -> pd.DataFrame:
    if not CHECKPOINT_CSV.is_file():
        return pd.DataFrame(columns=DAILY_COLUMNS)

    frame = pd.read_csv(CHECKPOINT_CSV)

    required = set(DAILY_COLUMNS)
    missing = required.difference(frame.columns)

    if missing:
        raise ValueError(
            "Checkpoint exists but is incompatible with Program 31 v1.0.1.\n"
            f"Missing columns: {sorted(missing)}\n"
            f"Checkpoint: {CHECKPOINT_CSV}"
        )

    frame["date"] = pd.to_datetime(frame["date"]).dt.strftime("%Y-%m-%d")

    print(
        f"Checkpoint loaded : {len(frame):,} completed date × threshold rows"
    )

    return frame[DAILY_COLUMNS].copy()


def completed_keys(frame: pd.DataFrame) -> set[tuple[str, float]]:
    if frame.empty:
        return set()

    return set(
        zip(
            frame["date"].astype(str),
            frame["threshold_c"].astype(float),
        )
    )


def write_checkpoint(records: list[dict]) -> None:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)

    frame = pd.DataFrame(records, columns=DAILY_COLUMNS)

    if frame.empty:
        return

    frame = (
        frame
        .drop_duplicates(subset=["date", "threshold_c"], keep="last")
        .sort_values(["date", "threshold_c"])
        .reset_index(drop=True)
    )

    frame.to_csv(
        CHECKPOINT_CSV,
        index=False,
        float_format="%.8f",
    )


# =============================================================================
# LONG-TERM PROCESSING
# =============================================================================

def process_full_record(common_dates: pd.DatetimeIndex) -> pd.DataFrame:
    """
    Process the complete daily record.

    NOTE
    ----
    Daily spatial SST fields are deliberately loaded through Program 17 so that
    Program 31 uses exactly the same grid alignment, fixed Pacific mask, SST
    conversion, and longitude convention as the validated methodological
    workflow.

    A checkpoint makes this long-running operation restartable.
    """
    checkpoint = load_checkpoint()

    records = (
        checkpoint.to_dict("records")
        if not checkpoint.empty
        else []
    )

    done = completed_keys(checkpoint)

    total_expected = len(common_dates) * len(THRESHOLDS_C)

    print()
    print("## PROCESSING COMPLETE DAILY RECORD")
    print()
    print(f"Expected diagnostics : {total_expected:,}")
    print(f"Already completed    : {len(done):,}")
    print()

    processed_dates_since_checkpoint = 0

    for index, date in enumerate(common_dates, start=1):
        date_string = f"{date:%Y-%m-%d}"

        missing_thresholds = [
            threshold
            for threshold in THRESHOLDS_C
            if (date_string, float(threshold)) not in done
        ]

        if not missing_thresholds:
            continue

        try:
            field = P17.load_daily_field(date)
            cell_areas = P17.spherical_cell_areas_km2(
                field.latitude,
                field.longitude,
            )

            for threshold in missing_thresholds:
                diagnostic = calculate_one(
                    field=field,
                    threshold_c=threshold,
                    cell_areas_km2=cell_areas,
                )

                record = asdict(diagnostic)
                records.append(record)
                done.add((date_string, float(threshold)))

            processed_dates_since_checkpoint += 1

            if (
                processed_dates_since_checkpoint >= CHECKPOINT_EVERY_DATES
                or index == len(common_dates)
            ):
                write_checkpoint(records)
                processed_dates_since_checkpoint = 0

            if index == 1 or index % 100 == 0 or index == len(common_dates):
                print(
                    f"{index:6,d}/{len(common_dates):,} | "
                    f"{date_string} | "
                    f"{len(done):,}/{total_expected:,} diagnostics"
                )

        except KeyboardInterrupt:
            write_checkpoint(records)
            print()
            print("Interrupted by user. Checkpoint saved.")
            raise

        except Exception:
            write_checkpoint(records)
            print()
            print(
                f"ERROR on {date_string}. Checkpoint saved before stopping."
            )
            raise

    final = pd.DataFrame(records, columns=DAILY_COLUMNS)

    final = (
        final
        .drop_duplicates(subset=["date", "threshold_c"], keep="last")
        .sort_values(["date", "threshold_c"])
        .reset_index(drop=True)
    )

    if len(final) != total_expected:
        raise RuntimeError(
            "Final daily table is incomplete.\n"
            f"Expected: {total_expected:,}\n"
            f"Found   : {len(final):,}"
        )

    TABLE_DIR.mkdir(parents=True, exist_ok=True)

    final.to_csv(
        DAILY_CSV,
        index=False,
        float_format="%.8f",
    )

    if CHECKPOINT_CSV.is_file():
        CHECKPOINT_CSV.unlink()

    return final


# =============================================================================
# SUMMARY TABLES
# =============================================================================

def pct(series: pd.Series, q: float) -> float:
    return float(series.quantile(q))


def build_threshold_summary(daily: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict] = []

    for threshold, group in daily.groupby("threshold_c", sort=True):
        fraction = group["largest_component_area_fraction"].astype(float)
        distance = group["centroid_distance_km"].astype(float)

        row = {
            "threshold_c": float(threshold),
            "n_days": int(len(group)),
            "start_date": str(group["date"].min()),
            "end_date": str(group["date"].max()),

            "component_count_median":
                float(group["component_count"].median()),

            "largest_fraction_mean": float(fraction.mean()),
            "largest_fraction_median": float(fraction.median()),
            "largest_fraction_p05": pct(fraction, 0.05),
            "largest_fraction_p25": pct(fraction, 0.25),
            "largest_fraction_p75": pct(fraction, 0.75),
            "largest_fraction_p95": pct(fraction, 0.95),

            "centroid_distance_km_mean": float(distance.mean()),
            "centroid_distance_km_median": float(distance.median()),
            "centroid_distance_km_p75": pct(distance, 0.75),
            "centroid_distance_km_p95": pct(distance, 0.95),
            "centroid_distance_km_p99": pct(distance, 0.99),
            "centroid_distance_km_max": float(distance.max()),
        }

        for level in AREA_FRACTION_LEVELS:
            key = f"pct_days_largest_fraction_lt_{int(level * 100):02d}"
            row[key] = float(100.0 * (fraction < level).mean())

        for level in CENTROID_DISTANCE_LEVELS_KM:
            key = f"pct_days_centroid_distance_gt_{int(level):04d}_km"
            row[key] = float(100.0 * (distance > level).mean())

        rows.append(row)

    summary = pd.DataFrame(rows)

    summary.to_csv(
        THRESHOLD_SUMMARY_CSV,
        index=False,
        float_format="%.8f",
    )

    return summary


def build_annual_summary(daily: pd.DataFrame) -> pd.DataFrame:
    frame = daily.copy()
    frame["date"] = pd.to_datetime(frame["date"])
    frame["year"] = frame["date"].dt.year

    rows: list[dict] = []

    for (year, threshold), group in frame.groupby(
        ["year", "threshold_c"],
        sort=True,
    ):
        fraction = group["largest_component_area_fraction"].astype(float)
        distance = group["centroid_distance_km"].astype(float)

        rows.append(
            {
                "year": int(year),
                "threshold_c": float(threshold),
                "n_days": int(len(group)),
                "largest_fraction_mean": float(fraction.mean()),
                "largest_fraction_median": float(fraction.median()),
                "largest_fraction_p05": pct(fraction, 0.05),
                "centroid_distance_km_mean": float(distance.mean()),
                "centroid_distance_km_median": float(distance.median()),
                "centroid_distance_km_p95": pct(distance, 0.95),
                "pct_days_largest_fraction_lt_90":
                    float(100.0 * (fraction < 0.90).mean()),
                "pct_days_centroid_distance_gt_500_km":
                    float(100.0 * (distance > 500.0).mean()),
                "pct_days_centroid_distance_gt_1000_km":
                    float(100.0 * (distance > 1000.0).mean()),
            }
        )

    annual = pd.DataFrame(rows)

    annual.to_csv(
        ANNUAL_SUMMARY_CSV,
        index=False,
        float_format="%.8f",
    )

    return annual


def build_extreme_days(daily: pd.DataFrame) -> pd.DataFrame:
    """
    Save the most informative fragmented / centroid-sensitive days.

    For each threshold:
        - 25 lowest largest-component fractions;
        - 25 greatest centroid separations.
    """
    selected: list[pd.DataFrame] = []

    for threshold, group in daily.groupby("threshold_c", sort=True):
        low_fraction = group.nsmallest(
            25,
            "largest_component_area_fraction",
        ).copy()
        low_fraction["selection_reason"] = "lowest_largest_component_fraction"

        high_distance = group.nlargest(
            25,
            "centroid_distance_km",
        ).copy()
        high_distance["selection_reason"] = "greatest_centroid_separation"

        selected.extend([low_fraction, high_distance])

    extremes = pd.concat(selected, ignore_index=True)

    extremes = (
        extremes
        .drop_duplicates(
            subset=["date", "threshold_c", "selection_reason"]
        )
        .sort_values(
            ["threshold_c", "selection_reason", "date"]
        )
        .reset_index(drop=True)
    )

    extremes.to_csv(
        EXTREME_DAYS_CSV,
        index=False,
        float_format="%.8f",
    )

    return extremes


# =============================================================================
# FIGURES
# =============================================================================

def save_figure(fig: plt.Figure, stem: str) -> tuple[Path, Path]:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)

    png = FIGURE_DIR / f"{stem}.png"
    pdf = FIGURE_DIR / f"{stem}.pdf"

    fig.savefig(
        png,
        dpi=FIGURE_DPI,
        bbox_inches=SAVE_BBOX,
        pad_inches=SAVE_PAD_INCHES,
        transparent=SAVE_TRANSPARENT,
    )

    fig.savefig(
        pdf,
        bbox_inches=SAVE_BBOX,
        pad_inches=SAVE_PAD_INCHES,
        transparent=SAVE_TRANSPARENT,
    )

    plt.close(fig)
    return png, pdf


def configure_date_axis(ax: plt.Axes) -> None:
    ax.xaxis.set_major_locator(mdates.YearLocator(base=4))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    ax.grid(alpha=0.20)


def figure_fraction_timeseries(daily: pd.DataFrame) -> tuple[Path, Path]:
    frame = daily.copy()
    frame["date"] = pd.to_datetime(frame["date"])

    fig, axes = plt.subplots(
        3,
        1,
        figsize=(13, 9),
        sharex=True,
        constrained_layout=True,
    )

    for ax, threshold in zip(axes, THRESHOLDS_C):
        group = frame[frame["threshold_c"] == threshold]

        ax.plot(
            group["date"],
            group["largest_component_area_fraction"] * 100.0,
            linewidth=0.55,
        )

        ax.axhline(90.0, linestyle="--", linewidth=0.9)
        ax.axhline(75.0, linestyle=":", linewidth=0.9)

        ax.set_ylabel("Largest component\n(% total area)")
        ax.set_title(f"{threshold:.1f} °C")
        ax.set_ylim(0.0, 101.0)
        configure_date_axis(ax)

    axes[-1].set_xlabel("Year")

    fig.suptitle(
        "Long-term spatial coherence of the Pacific Warm Pool",
        fontsize=14,
    )

    return save_figure(
        fig,
        "pwp_largest_component_fraction_timeseries",
    )


def figure_distance_timeseries(daily: pd.DataFrame) -> tuple[Path, Path]:
    frame = daily.copy()
    frame["date"] = pd.to_datetime(frame["date"])

    fig, axes = plt.subplots(
        3,
        1,
        figsize=(13, 9),
        sharex=True,
        constrained_layout=True,
    )

    for ax, threshold in zip(axes, THRESHOLDS_C):
        group = frame[frame["threshold_c"] == threshold]

        ax.plot(
            group["date"],
            group["centroid_distance_km"],
            linewidth=0.55,
        )

        ax.axhline(500.0, linestyle="--", linewidth=0.9)
        ax.axhline(1000.0, linestyle=":", linewidth=0.9)

        ax.set_ylabel("Centroid separation\n(km)")
        ax.set_title(f"{threshold:.1f} °C")
        configure_date_axis(ax)

    axes[-1].set_xlabel("Year")

    fig.suptitle(
        "Sensitivity of PWP centroid to disconnected warm-water components",
        fontsize=14,
    )

    return save_figure(
        fig,
        "pwp_centroid_separation_timeseries",
    )


def figure_distributions(daily: pd.DataFrame) -> tuple[Path, Path]:
    fig, axes = plt.subplots(
        2,
        1,
        figsize=(10, 9),
        constrained_layout=True,
    )

    bins_fraction = np.linspace(0.0, 1.0, 51)

    max_distance = float(
        daily["centroid_distance_km"].quantile(0.995)
    )
    max_distance = max(max_distance, 1000.0)
    bins_distance = np.linspace(0.0, max_distance, 60)

    for threshold in THRESHOLDS_C:
        group = daily[daily["threshold_c"] == threshold]

        axes[0].hist(
            group["largest_component_area_fraction"],
            bins=bins_fraction,
            histtype="step",
            density=True,
            linewidth=1.4,
            label=f"{threshold:.1f} °C",
        )

        clipped = group["centroid_distance_km"].clip(
            upper=max_distance
        )

        axes[1].hist(
            clipped,
            bins=bins_distance,
            histtype="step",
            density=True,
            linewidth=1.4,
            label=f"{threshold:.1f} °C",
        )

    axes[0].set_xlabel("Largest-component fraction of total PWP area")
    axes[0].set_ylabel("Density")
    axes[0].grid(alpha=0.20)
    axes[0].legend(frameon=False)

    axes[1].set_xlabel("Full vs largest-component centroid separation (km)")
    axes[1].set_ylabel("Density")
    axes[1].grid(alpha=0.20)
    axes[1].legend(frameon=False)

    fig.suptitle(
        "Threshold sensitivity of PWP spatial connectivity",
        fontsize=14,
    )

    return save_figure(
        fig,
        "pwp_connectivity_threshold_distributions",
    )


def figure_summary(summary: pd.DataFrame) -> tuple[Path, Path]:
    thresholds = summary["threshold_c"].to_numpy(float)

    fig, axes = plt.subplots(
        2,
        1,
        figsize=(9, 8),
        constrained_layout=True,
    )

    axes[0].plot(
        thresholds,
        summary["largest_fraction_median"] * 100.0,
        marker="o",
        label="Median",
    )
    axes[0].plot(
        thresholds,
        summary["largest_fraction_p05"] * 100.0,
        marker="s",
        label="5th percentile",
    )

    axes[0].set_ylabel("Largest component (% total area)")
    axes[0].set_xticks(thresholds)
    axes[0].set_xlabel("SST threshold (°C)")
    axes[0].grid(alpha=0.20)
    axes[0].legend(frameon=False)

    axes[1].plot(
        thresholds,
        summary["centroid_distance_km_median"],
        marker="o",
        label="Median",
    )
    axes[1].plot(
        thresholds,
        summary["centroid_distance_km_p95"],
        marker="s",
        label="95th percentile",
    )

    axes[1].set_ylabel("Centroid separation (km)")
    axes[1].set_xticks(thresholds)
    axes[1].set_xlabel("SST threshold (°C)")
    axes[1].grid(alpha=0.20)
    axes[1].legend(frameon=False)

    fig.suptitle(
        "Long-term threshold robustness of the PWP centroid",
        fontsize=14,
    )

    return save_figure(
        fig,
        "pwp_connectivity_threshold_summary",
    )


# =============================================================================
# TERMINAL SUMMARY
# =============================================================================

def print_scientific_summary(summary: pd.DataFrame) -> None:
    print()
    print("## LONG-TERM THRESHOLD SUMMARY")
    print()

    for _, row in summary.iterrows():
        threshold = float(row["threshold_c"])

        print(f"{threshold:.1f} °C")
        print(
            "  Largest-component fraction | "
            f"median={row['largest_fraction_median'] * 100.0:6.2f}% | "
            f"P05={row['largest_fraction_p05'] * 100.0:6.2f}%"
        )
        print(
            "  Centroid separation         | "
            f"median={row['centroid_distance_km_median']:8.1f} km | "
            f"P95={row['centroid_distance_km_p95']:8.1f} km | "
            f"max={row['centroid_distance_km_max']:8.1f} km"
        )
        print(
            "  Days largest component <90% | "
            f"{row['pct_days_largest_fraction_lt_90']:6.2f}%"
        )
        print(
            "  Days separation >500 km     | "
            f"{row['pct_days_centroid_distance_gt_0500_km']:6.2f}%"
        )
        print(
            "  Days separation >1000 km    | "
            f"{row['pct_days_centroid_distance_gt_1000_km']:6.2f}%"
        )
        print()


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    print("=" * 78)
    print(PROGRAM_NAME)
    print("=" * 78)
    print()

    print("## CONFIGURATION")
    print()
    print(f"Program version                  : {PROGRAM_VERSION}")
    print(f"Project root                     : {PROJECT_ROOT}")
    print(f"Program-17 source                : {PROGRAM17_FILE}")
    print("Thresholds                       : 28.0, 28.5, 29.0 °C")
    print(f"Connectivity                     : {CONNECTIVITY_LABEL}")
    print("Component ranking                : spherical area")
    print("Temporal resolution              : daily")
    print("Climate-index upsampling         : prohibited")
    print(f"Checkpoint interval              : {CHECKPOINT_EVERY_DATES} processed dates")
    print(f"Table directory                  : {TABLE_DIR}")
    print(f"Figure directory                 : {FIGURE_DIR}")
    print()

    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)

    # Use Program 17's own configuration validation.
    P17.validate_configuration()

    common_dates = load_common_dates()

    daily = process_full_record(common_dates)

    print()
    print("## BUILDING SUMMARY TABLES")
    print()

    threshold_summary = build_threshold_summary(daily)
    annual_summary = build_annual_summary(daily)
    extreme_days = build_extreme_days(daily)

    print(DAILY_CSV)
    print(THRESHOLD_SUMMARY_CSV)
    print(ANNUAL_SUMMARY_CSV)
    print(EXTREME_DAYS_CSV)

    print()
    print("## GENERATING FIGURES")
    print()

    figure_files: list[Path] = []

    for files in (
        figure_fraction_timeseries(daily),
        figure_distance_timeseries(daily),
        figure_distributions(daily),
        figure_summary(threshold_summary),
    ):
        figure_files.extend(files)

    for path in figure_files:
        print(path)

    print_scientific_summary(threshold_summary)

    print("=" * 78)
    print("PROGRAM 31 COMPLETED SUCCESSFULLY.")
    print()
    print(
        "The complete daily record was evaluated for 28.0, 28.5, and 29.0 °C."
    )
    print(
        "Use the threshold summary, annual summary, extreme-day table, and "
        "figures to make the final scientific threshold decision."
    )
    print(
        "Program 31 does not alter the authoritative Program-05 centroid series."
    )
    print("=" * 78)


if __name__ == "__main__":
    main()
