#!/usr/bin/env python3
# -*- coding: utf-8 -*-

r"""
===============================================================================
PROJECT
    Ocean Spectral Analysis Framework (OSAF)
    Pacific Warm Pool (PWP) Scientific Analysis Pipeline

PROGRAM
    34_pwp_domain_size_centroid_displacement_sensitivity_v1.01.py

TITLE
    PWP Domain Size × Centroid Displacement Sensitivity

VERSION
    1.01

AUTHOR
    Fabio Vieira Machado

PYTHON
    Python 3.10+

===============================================================================
PURPOSE
===============================================================================

Program 34 is the final compact geometric diagnostic for the first PWP
threshold-definition paper. It quantifies how the size of the thermal domain
associated with 28.0, 28.5 and 29.0 °C relates to the amplitude and
geographical expression of centroid variability.

Primary descriptive hypothesis:

    larger threshold-defined warm-water domain
        -> greater spatial integration
        -> potentially lower geometric sensitivity of its centroid
           to localized spatial reorganizations.

This program tests GEOMETRIC / STATISTICAL centroid sensitivity only.
It does NOT demonstrate greater physical or dynamical inertia of the water
mass and does not estimate momentum, heat content, mixed-layer depth,
circulation, or forcing.

Version 1.01 is a PUBLICATION-DIAGNOSTIC EXTENSION of the frozen Program 34.
It preserves all Program-34 calculations and adds, without recomputing the
PWP definition:

    1. full-record spatial distributions of the canonical daily spherical
       centroids for 28.0, 28.5 and 29.0 °C;
    2. point colour proportional to daily PWP area (10^6 km^2);
    3. a long-term mean spherical centroid calculated from the daily centroid
       unit vectors, never from arithmetic longitude/latitude means;
    4. a fourth comparison panel using 2-D density contours to avoid excessive
       overplotting;
    5. a publication-oriented spatial-summary table;
    6. an explicit daily inter-threshold centroid-separation time-series CSV.

No legacy centroid product is read and no daily SST thresholding is repeated
in this version. The canonical Program-05 frozen centroid files remain the
sole upstream spatial input.

Preferred interpretation:

    "reduced centroid sensitivity resulting from spatial integration over a
     larger warm-water domain"

rather than:

    "greater dynamical inertia of the 28 °C PWP."

===============================================================================
SCIENTIFIC CONTEXT
===============================================================================

Approximately:

    PWP_29 ⊂ PWP_28.5 ⊂ PWP_28

but this does NOT imply:

    r_c,29 = r_c,28.5 = r_c,28

because each threshold integrates a distinct set of grid cells with different
area, geometry, connectivity and spatial weighting. Thus the three centroids
are three different geographical observables of the same coupled tropical
Pacific climate system, not noisy estimates of a single true point.

In simplified planar notation only for conceptual illustration:

                      A_29 r_29 + A_28-29 r_28-29
    r_28  ≈  ------------------------------------------
                           A_29 + A_28-29

The authoritative OSAF centroid itself is spherical, not planar.

===============================================================================
PRIMARY QUESTIONS
===============================================================================

Q1. How does PWP domain area change from 28 -> 28.5 -> 29 °C?

Q2. How does longitudinal centroid-displacement amplitude change across
    thresholds?

        standard deviation
        IQR
        P05-P95 robust amplitude
        full range

Q3. How does meridional amplitude change across thresholds?

Q4. Relative to each threshold's own long-term spherical reference centroid,
    how large is the daily two-dimensional great-circle excursion?

Q5. How far apart are the 28, 28.5 and 29 °C centroids on the SAME day?

Q6. Do the results support a simple inverse domain-size / centroid-amplitude
    ordering, or do they show that geometry/connectivity/asymmetry also matter?

===============================================================================
AUTHORITATIVE INPUT DATA
===============================================================================

Generated by OSAF PROGRAM 05:

    src_a/05_calculate_pwp_centroid.py

Input files:

    data/processed/28/centroid/pwp_centroid_series.csv
    data/processed/28.5/centroid/pwp_centroid_series.csv
    data/processed/29/centroid/pwp_centroid_series.csv

Confirmed Program-05 columns:

    date
    lon_360
    lon_180
    lat
    area_km2
    pwp_cell_count
    valid_ocean_cell_count
    mask_cell_count
    ocean_data_coverage_pct
    mean_pwp_sst_c
    max_pwp_sst_c
    area_weighted_sst_std_c
    threshold_c
    threshold_source
    threshold_fallback_used
    centroid_resultant_length
    centroid_angular_dispersion_deg
    quality_flag
    source_file

Program 05 derives these series from daily NOAA OISST, the fixed validated
Pacific mask and the absolute-SST threshold. Program 34 does not recalculate
SST fields or daily centroids.

===============================================================================
QUALITY-CONTROL POLICY
===============================================================================

Program 05 originally used a 99% daily-coverage flag, so its files may contain
quality_flag = LOW_COVERAGE even when coverage is approximately 98.0678%.
Program 06 subsequently adopted the final operational criterion of 98.0% for
the legacy-mask/OISST pairing.

Therefore Program 34 DOES NOT reject a row merely because the original string
contains LOW_COVERAGE.

Program 34 requires:

    ocean_data_coverage_pct >= 98.0
    finite area_km2
    finite lon_360
    finite lat
    threshold_fallback_used == False
    no NO_PWP_CELLS flag

Only dates common to all three thresholds after this QC are compared.

===============================================================================
MATHEMATICAL DEFINITIONS
===============================================================================

1. PWP total area is inherited from Program 05:

        A_PWP(t;T) = Σ_i A_i I_i(t;T)

2. Long-term threshold-specific spherical reference centroid:

        x_t = cos(phi_t) cos(lambda_t)
        y_t = cos(phi_t) sin(lambda_t)
        z_t = sin(phi_t)

        X = mean(x_t), Y = mean(y_t), Z = mean(z_t)

        lambda_ref = atan2(Y, X)
        phi_ref    = atan2(Z, sqrt(X^2 + Y^2))

3. Great-circle distance (haversine):

        a = sin²(Delta_phi/2)
            + cos(phi_1) cos(phi_2) sin²(Delta_lambda/2)

        d = 2 R asin(sqrt(a))

    with R = 6371.0088 km.

4. Robust longitudinal amplitude:

        R_lambda(T) = P95[lambda_T(t)] - P05[lambda_T(t)]

5. Robust latitudinal amplitude:

        R_phi(T) = P95[phi_T(t)] - P05[phi_T(t)]

6. Radial centroid excursion:

        D_T(t) = great-circle distance between the daily centroid and the
                 threshold-specific long-term spherical reference centroid.

7. Inter-threshold centroid separation:

        D_T1,T2(t) = great-circle distance between the two threshold-specific
                     centroids on the same date.

===============================================================================
WHY NO THRESHOLD-LEVEL P-VALUE
===============================================================================

There are only three threshold definitions. Program 34 deliberately reports
effect sizes, ratios, percentage changes and monotonic ordering rather than a
regression/p-value based on only three threshold-level points.

This avoids false statistical precision.

===============================================================================
CONNECTION TO PROGRAMS 31 AND 32
===============================================================================

Program 31:
    threshold-sensitive connectivity and full-domain versus largest-component
    centroid robustness.

Program 32:
    threshold-robust timing of annual/interannual wavelet-band variance,
    especially very high interannual cross-threshold correlations.

Program 34:
    threshold-sensitive domain size, centroid amplitude and geographical
    non-coincidence.

Conceptual paper framework:

    threshold-sensitive geometry / amplitude

                    versus

    threshold-robust interannual temporal organization.

===============================================================================
OUTPUTS
===============================================================================

TABLES
    outputs/tables/threshold_comparison/
        pwp_domain_size_centroid_sensitivity/

    pwp_domain_size_centroid_sensitivity_summary.csv
    pwp_interthreshold_centroid_separation_summary.csv
    pwp_domain_size_centroid_sensitivity_daily.csv

FIGURES
    outputs/figures/threshold_comparison/
        pwp_domain_size_centroid_sensitivity/

    pwp_domain_size_centroid_sensitivity_summary.png/.pdf
        A) mean PWP area
        B) longitude P95-P05 amplitude
        C) P95 radial centroid excursion

    pwp_interthreshold_centroid_separation_timeseries.png/.pdf
        A) 28 vs 28.5 °C
        B) 28 vs 29 °C
        C) 28.5 vs 29 °C

REPORTS
    outputs/reports/threshold_comparison/
        pwp_domain_size_centroid_sensitivity/

    PROGRAM34_PWP_DOMAIN_SIZE_CENTROID_SENSITIVITY.txt
    PROGRAM34_PWP_DOMAIN_SIZE_CENTROID_SENSITIVITY.json

===============================================================================
INTERPRETATION POLICY
===============================================================================

ALLOWED:
    different thresholds define distinct thermal domains;
    different thresholds have different centroid locations;
    threshold choice affects centroid displacement amplitude;
    a broader domain can reduce centroid sensitivity through spatial
    integration;
    pairwise centroid separation quantifies geographical non-coincidence.

NOT ESTABLISHED BY PROGRAM 34:
    28 °C has greater physical inertia;
    29 °C is more strongly forced by ENSO because its power is larger;
    centroid amplitude directly measures forcing strength;
    area alone controls centroid sensitivity;
    threshold geometry proves an ocean-dynamical mechanism.

===============================================================================
EXECUTION
===============================================================================

    python src/threshold_analysis/34_pwp_domain_size_centroid_displacement_sensitivity_v1.01.py

===============================================================================
"""

from __future__ import annotations

import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# =============================================================================
# PROJECT / CONFIGURATION
# =============================================================================

SCRIPT_FILE = Path(__file__).resolve()
PROJECT_ROOT = SCRIPT_FILE.parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

try:
    from config.config import (
        FIGURE_DPI,
        GRID_ALPHA,
        GRID_LINESTYLE,
        GRID_LINEWIDTH,
        PROJECT_DIR,
        SAVE_BBOX,
        SAVE_PAD_INCHES,
        SAVE_TRANSPARENT,
        validate_project_configuration,
    )
except Exception as error:
    raise RuntimeError(
        "Unable to import canonical OSAF configuration for Program 34.\n"
        f"Expected project root: {PROJECT_ROOT}\n"
        f"Original error: {type(error).__name__}: {error}"
    ) from error

PROGRAM_NAME = "OSAF PROGRAM 34 — PWP DOMAIN SIZE × CENTROID DISPLACEMENT SENSITIVITY"
PROGRAM_VERSION = "1.01"

THRESHOLDS_C = (28.0, 28.5, 29.0)
PRIMARY_THRESHOLD_C = 28.0
EARTH_RADIUS_KM = 6371.0088
FINAL_MINIMUM_COVERAGE_PCT = 98.0
YEAR_TICK_ANCHOR = 1982
YEAR_TICK_INTERVAL = 4

INPUT_FILES = {
    28.0: Path(PROJECT_DIR) / "data" / "processed" / "28" / "centroid" / "pwp_centroid_series.csv",
    28.5: Path(PROJECT_DIR) / "data" / "processed" / "28.5" / "centroid" / "pwp_centroid_series.csv",
    29.0: Path(PROJECT_DIR) / "data" / "processed" / "29" / "centroid" / "pwp_centroid_series.csv",
}

TABLE_DIR = Path(PROJECT_DIR) / "outputs" / "tables" / "threshold_comparison" / "pwp_domain_size_centroid_sensitivity"
FIGURE_DIR = Path(PROJECT_DIR) / "outputs" / "figures" / "threshold_comparison" / "pwp_domain_size_centroid_sensitivity"
REPORT_DIR = Path(PROJECT_DIR) / "outputs" / "reports" / "threshold_comparison" / "pwp_domain_size_centroid_sensitivity"

SUMMARY_FILE = TABLE_DIR / "pwp_domain_size_centroid_sensitivity_summary.csv"
PAIRWISE_FILE = TABLE_DIR / "pwp_interthreshold_centroid_separation_summary.csv"
DAILY_FILE = TABLE_DIR / "pwp_domain_size_centroid_sensitivity_daily.csv"

SPATIAL_SUMMARY_FILE = TABLE_DIR / "pwp_centroid_spatial_distribution_summary.csv"
SEPARATION_TIMESERIES_FILE = TABLE_DIR / "pwp_interthreshold_centroid_separation_timeseries.csv"
REPORT_TXT = REPORT_DIR / "PROGRAM34_PWP_DOMAIN_SIZE_CENTROID_SENSITIVITY.txt"
REPORT_JSON = REPORT_DIR / "PROGRAM34_PWP_DOMAIN_SIZE_CENTROID_SENSITIVITY.json"

REQUIRED_COLUMNS = (
    "date", "lon_360", "lon_180", "lat", "area_km2", "pwp_cell_count",
    "valid_ocean_cell_count", "mask_cell_count", "ocean_data_coverage_pct",
    "mean_pwp_sst_c", "max_pwp_sst_c", "area_weighted_sst_std_c",
    "threshold_c", "threshold_source", "threshold_fallback_used",
    "centroid_resultant_length", "centroid_angular_dispersion_deg",
    "quality_flag", "source_file",
)


# =============================================================================
# UTILITIES
# =============================================================================

def rule(character="=", width=78):
    print(character * width)


def section(title):
    print()
    print(title)
    rule("-")


def item(label, value):
    print(f"{label:<48s}: {value}")


def threshold_tag(t):
    return f"{t:.1f}".replace(".", "p") + "C"


def parse_bool_series(series):
    if pd.api.types.is_bool_dtype(series):
        return series.astype(bool)
    return series.astype(str).str.strip().str.lower().isin(("true", "1", "yes", "y"))


def finite(values):
    x = np.asarray(values, dtype=float)
    return x[np.isfinite(x)]


def fmean(values):
    x = finite(values)
    return float(np.mean(x)) if x.size else np.nan


def fmedian(values):
    x = finite(values)
    return float(np.median(x)) if x.size else np.nan


def fstd(values):
    x = finite(values)
    return float(np.std(x, ddof=1)) if x.size >= 2 else np.nan


def fq(values, q):
    x = finite(values)
    return float(np.quantile(x, q)) if x.size else np.nan


def unwrap_longitude_deg(lon360):
    lon = np.asarray(lon360, dtype=float)
    u = np.rad2deg(np.unwrap(np.deg2rad(lon)))
    if np.isfinite(np.nanmedian(lon)) and np.isfinite(np.nanmedian(u)):
        shift = np.round((np.nanmedian(u) - np.nanmedian(lon)) / 360.0)
        u = u - 360.0 * shift
    return u


def wrap_delta_longitude_deg(delta):
    return ((np.asarray(delta, dtype=float) + 180.0) % 360.0) - 180.0


def spherical_reference_centroid(lon_deg, lat_deg):
    lon = np.deg2rad(np.asarray(lon_deg, dtype=float))
    lat = np.deg2rad(np.asarray(lat_deg, dtype=float))
    ok = np.isfinite(lon) & np.isfinite(lat)
    lon, lat = lon[ok], lat[ok]
    x = np.cos(lat) * np.cos(lon)
    y = np.cos(lat) * np.sin(lon)
    z = np.sin(lat)
    X, Y, Z = float(np.mean(x)), float(np.mean(y)), float(np.mean(z))
    resultant = float(np.sqrt(X * X + Y * Y + Z * Z))
    lon_ref = math.degrees(math.atan2(Y, X)) % 360.0
    lat_ref = math.degrees(math.atan2(Z, math.sqrt(X * X + Y * Y)))
    return lon_ref, lat_ref, resultant


def great_circle_distance_km(lon1, lat1, lon2, lat2):
    lon1 = np.deg2rad(np.asarray(lon1, dtype=float))
    lat1 = np.deg2rad(np.asarray(lat1, dtype=float))
    lon2 = np.deg2rad(np.asarray(lon2, dtype=float))
    lat2 = np.deg2rad(np.asarray(lat2, dtype=float))
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat / 2.0) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0) ** 2
    a = np.clip(a, 0.0, 1.0)
    return 2.0 * EARTH_RADIUS_KM * np.arcsin(np.sqrt(a))


def add_panel_label(ax, text):
    ax.text(0.01, 0.96, text, transform=ax.transAxes, ha="left", va="top", fontsize=11, fontweight="bold")


def save_figure(fig, stem):
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    png = FIGURE_DIR / f"{stem}.png"
    pdf = FIGURE_DIR / f"{stem}.pdf"
    fig.savefig(png, dpi=FIGURE_DPI, bbox_inches=SAVE_BBOX, pad_inches=SAVE_PAD_INCHES, transparent=SAVE_TRANSPARENT)
    fig.savefig(pdf, bbox_inches=SAVE_BBOX, pad_inches=SAVE_PAD_INCHES, transparent=SAVE_TRANSPARENT)
    plt.close(fig)
    return png, pdf



# =============================================================================
# PUBLICATION SPATIAL-DISTRIBUTION EXTENSION — VERSION 1.01
# =============================================================================

def build_spatial_distribution_summary(series):
    """
    Build publication-oriented statistics for the canonical daily centroid
    populations.

    The long-term mean centroid is calculated correctly on the sphere:
    daily centroid lon/lat -> 3-D unit vectors -> mean vector -> lon/lat.

    It is NOT the arithmetic mean of longitude and latitude.
    """
    rows = []

    for threshold_c in THRESHOLDS_C:
        data = series[threshold_c]

        lon_360 = data["lon_360"].to_numpy(dtype=float)
        lon_unwrapped = data["lon_unwrapped_deg"].to_numpy(dtype=float)
        lat = data["lat"].to_numpy(dtype=float)
        area = data["area_km2"].to_numpy(dtype=float)

        mean_lon, mean_lat, resultant = spherical_reference_centroid(
            lon_360,
            lat,
        )

        rows.append(
            {
                "threshold_c": threshold_c,
                "n_days": int(len(data)),
                "start_date": data["date"].min(),
                "end_date": data["date"].max(),
                "mean_spherical_lon_360_deg": mean_lon,
                "mean_spherical_lat_deg": mean_lat,
                "mean_spherical_resultant_length": resultant,
                "median_longitude_deg": fmedian(lon_unwrapped),
                "median_latitude_deg": fmedian(lat),
                "longitude_p05_deg": fq(lon_unwrapped, 0.05),
                "longitude_p95_deg": fq(lon_unwrapped, 0.95),
                "latitude_p05_deg": fq(lat, 0.05),
                "latitude_p95_deg": fq(lat, 0.95),
                "mean_daily_pwp_area_km2": fmean(area),
                "median_daily_pwp_area_km2": fmedian(area),
                "mean_daily_pwp_area_million_km2": fmean(area) / 1.0e6,
                "median_daily_pwp_area_million_km2": fmedian(area) / 1.0e6,
                "source_program": "OSAF Program 05",
                "analysis_program": "OSAF Program 34 v1.01",
                "source_file": str(INPUT_FILES[threshold_c]),
                "centroid_method": (
                    "daily area-weighted spherical centroid; "
                    "long-term mean from mean 3-D unit vector"
                ),
                "provenance_policy": (
                    "canonical frozen centroid products only; "
                    "PWP definition not recomputed"
                ),
            }
        )

    return (
        pd.DataFrame(rows)
        .sort_values("threshold_c")
        .reset_index(drop=True)
    )


def export_spatial_distribution_summary(spatial_summary):
    """Export the requested publication-oriented spatial summary table."""
    TABLE_DIR.mkdir(parents=True, exist_ok=True)

    output = spatial_summary.copy()

    for column in ("start_date", "end_date"):
        output[column] = pd.to_datetime(output[column]).dt.strftime("%Y-%m-%d")

    output.to_csv(
        SPATIAL_SUMMARY_FILE,
        index=False,
        float_format="%.10g",
    )

    return SPATIAL_SUMMARY_FILE


def export_interthreshold_separation_timeseries(daily):
    """
    Export the explicit daily same-date inter-threshold centroid-separation
    series used by the Program-34 figure.
    """
    pair_specs = (
        (28.0, 28.5),
        (28.0, 29.0),
        (28.5, 29.0),
    )

    columns = ["date"]

    for first, second in pair_specs:
        first_tag = threshold_tag(first)
        second_tag = threshold_tag(second)
        pair_tag = f"{first_tag}_vs_{second_tag}"

        columns.extend(
            [
                f"centroid_separation_km_{pair_tag}",
                f"delta_lon_deg_{pair_tag}",
                f"delta_lat_deg_{pair_tag}",
            ]
        )

    output = daily[columns].copy()
    output["date"] = pd.to_datetime(output["date"]).dt.strftime("%Y-%m-%d")

    output.insert(
        1,
        "source_program",
        "OSAF Program 34 v1.01",
    )
    output.insert(
        2,
        "provenance",
        (
            "derived exclusively from canonical frozen Program-05 "
            "daily centroid products"
        ),
    )

    output.to_csv(
        SEPARATION_TIMESERIES_FILE,
        index=False,
        float_format="%.10g",
    )

    return SEPARATION_TIMESERIES_FILE


def common_spatial_limits(series):
    """Return common longitude/latitude limits for all centroid panels."""
    all_lon = np.concatenate(
        [
            series[t]["lon_unwrapped_deg"].to_numpy(dtype=float)
            for t in THRESHOLDS_C
        ]
    )

    all_lat = np.concatenate(
        [
            series[t]["lat"].to_numpy(dtype=float)
            for t in THRESHOLDS_C
        ]
    )

    lon_min = float(np.nanmin(all_lon))
    lon_max = float(np.nanmax(all_lon))
    lat_min = float(np.nanmin(all_lat))
    lat_max = float(np.nanmax(all_lat))

    lon_margin = max(2.0, 0.04 * (lon_max - lon_min))
    lat_margin = max(1.0, 0.05 * (lat_max - lat_min))

    return (
        (lon_min - lon_margin, lon_max + lon_margin),
        (lat_min - lat_margin, lat_max + lat_margin),
    )


def histogram_density_contours(
    axis,
    lon,
    lat,
    levels=5,
    bins=(95, 70),
    label=None,
):
    """
    Draw descriptive 2-D density contours using a normalized histogram.

    No fitted probability model is assumed and no SciPy dependency is needed.
    """
    hist, x_edges, y_edges = np.histogram2d(
        lon,
        lat,
        bins=bins,
        density=True,
    )

    x_centres = 0.5 * (x_edges[:-1] + x_edges[1:])
    y_centres = 0.5 * (y_edges[:-1] + y_edges[1:])

    positive = hist[hist > 0.0]

    if positive.size == 0:
        return None

    q = np.linspace(0.45, 0.92, levels)
    contour_levels = np.unique(np.quantile(positive, q))

    if contour_levels.size < 2:
        return None

    cs = axis.contour(
        x_centres,
        y_centres,
        hist.T,
        levels=contour_levels,
        linewidths=1.15,
    )

    # Matplotlib versions differ in whether QuadContourSet exposes
    # .collections. Use a proxy artist for the legend instead.
    if label:
        axis.plot(
            [],
            [],
            linewidth=1.15,
            label=label,
        )

    return cs


def _mean_lon_on_data_branch(mean_lon_360, lon_unwrapped):
    """Map a 0-360 spherical-mean longitude onto the plotted unwrap branch."""
    mean_lon = float(mean_lon_360)
    data_median = float(np.nanmedian(lon_unwrapped))

    while mean_lon - data_median > 180.0:
        mean_lon -= 360.0

    while mean_lon - data_median < -180.0:
        mean_lon += 360.0

    return mean_lon


def plot_centroid_spatial_distribution(series, spatial_summary):
    """
    Create the requested publication-quality four-panel diagnostic.

    A-C:
        full daily centroid populations for 28.0, 28.5 and 29.0 °C;
        point colour = corresponding daily PWP area in 10^6 km²;
        identical longitude/latitude limits.

    D:
        combined threshold comparison using descriptive 2-D density contours.

    All panels mark the threshold-specific long-term mean spherical centroid.
    """
    lon_limits, lat_limits = common_spatial_limits(series)

    all_area_million = np.concatenate(
        [
            series[t]["area_km2"].to_numpy(dtype=float) / 1.0e6
            for t in THRESHOLDS_C
        ]
    )

    area_min = float(np.nanmin(all_area_million))
    area_max = float(np.nanmax(all_area_million))

    figure, axes = plt.subplots(
        nrows=2,
        ncols=2,
        figsize=(14.5, 10.8),
        constrained_layout=True,
    )

    flat_axes = axes.ravel()
    scatter_for_colorbar = None

    for index, threshold_c in enumerate(THRESHOLDS_C):
        axis = flat_axes[index]
        data = series[threshold_c]

        lon = data["lon_unwrapped_deg"].to_numpy(dtype=float)
        lat = data["lat"].to_numpy(dtype=float)
        area_million = data["area_km2"].to_numpy(dtype=float) / 1.0e6

        scatter_for_colorbar = axis.scatter(
            lon,
            lat,
            c=area_million,
            s=7.0,
            alpha=0.38,
            linewidths=0.0,
            rasterized=True,
            vmin=area_min,
            vmax=area_max,
        )

        row = spatial_summary.loc[
            np.isclose(
                spatial_summary["threshold_c"].to_numpy(dtype=float),
                threshold_c,
            )
        ].iloc[0]

        mean_lon = _mean_lon_on_data_branch(
            row["mean_spherical_lon_360_deg"],
            lon,
        )

        axis.scatter(
            [mean_lon],
            [float(row["mean_spherical_lat_deg"])],
            marker="*",
            s=240,
            edgecolors="black",
            linewidths=1.0,
            label="Mean spherical centroid",
            zorder=10,
        )

        axis.set_xlim(*lon_limits)
        axis.set_ylim(*lat_limits)
        axis.set_xlabel("Spherical centroid longitude (°E)")
        axis.set_ylabel("Spherical centroid latitude (°N)")
        axis.set_title(f"SST ≥ {threshold_c:.1f} °C")

        axis.grid(
            linestyle=GRID_LINESTYLE,
            linewidth=GRID_LINEWIDTH,
            alpha=GRID_ALPHA,
        )

        axis.legend(
            frameon=False,
            loc="best",
        )

        add_panel_label(
            axis,
            f"{chr(65 + index)})",
        )

    comparison_axis = flat_axes[3]

    for threshold_c in THRESHOLDS_C:
        data = series[threshold_c]

        lon = data["lon_unwrapped_deg"].to_numpy(dtype=float)
        lat = data["lat"].to_numpy(dtype=float)

        histogram_density_contours(
            comparison_axis,
            lon,
            lat,
            levels=5,
            bins=(95, 70),
            label=f"{threshold_c:.1f} °C density",
        )

        row = spatial_summary.loc[
            np.isclose(
                spatial_summary["threshold_c"].to_numpy(dtype=float),
                threshold_c,
            )
        ].iloc[0]

        mean_lon = _mean_lon_on_data_branch(
            row["mean_spherical_lon_360_deg"],
            lon,
        )

        comparison_axis.scatter(
            [mean_lon],
            [float(row["mean_spherical_lat_deg"])],
            marker="*",
            s=250,
            edgecolors="black",
            linewidths=1.0,
            label=f"{threshold_c:.1f} °C mean",
            zorder=10,
        )

    comparison_axis.set_xlim(*lon_limits)
    comparison_axis.set_ylim(*lat_limits)
    comparison_axis.set_xlabel("Spherical centroid longitude (°E)")
    comparison_axis.set_ylabel("Spherical centroid latitude (°N)")
    comparison_axis.set_title(
        "Cross-threshold centroid-population comparison"
    )

    comparison_axis.grid(
        linestyle=GRID_LINESTYLE,
        linewidth=GRID_LINEWIDTH,
        alpha=GRID_ALPHA,
    )

    comparison_axis.legend(
        frameon=False,
        loc="best",
        fontsize=8.5,
        ncol=2,
    )

    add_panel_label(
        comparison_axis,
        "D)",
    )

    if scatter_for_colorbar is not None:
        colorbar = figure.colorbar(
            scatter_for_colorbar,
            ax=flat_axes[:3].tolist(),
            shrink=0.88,
            pad=0.018,
        )

        colorbar.set_label(
            "Daily PWP area (10⁶ km²)"
        )

    figure.suptitle(
        (
            "Spatial distribution of daily spherical Pacific Warm Pool "
            "centroids, 1981-09-01 to 2026-07-29"
        ),
        fontsize=14,
    )

    return save_figure(
        figure,
        "pwp_centroid_spatial_distribution_threshold_comparison",
    )



# =============================================================================
# INPUT / QC
# =============================================================================

def validate_configuration():
    if Path(PROJECT_DIR).resolve() != PROJECT_ROOT.resolve():
        raise ValueError(
            "Project-root mismatch:\n"
            f"  config.PROJECT_DIR : {PROJECT_DIR}\n"
            f"  script root        : {PROJECT_ROOT}"
        )
    validate_project_configuration()
    for directory in (TABLE_DIR, FIGURE_DIR, REPORT_DIR):
        directory.mkdir(parents=True, exist_ok=True)
    for t, source in INPUT_FILES.items():
        if not source.is_file():
            raise FileNotFoundError(f"Missing Program-05 file for {t:.1f} °C:\n{source}")


def load_threshold_series(threshold_c, source):
    df = pd.read_csv(source, low_memory=False)
    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise KeyError(f"Missing columns in {source}: {missing}")

    df["date"] = pd.to_datetime(df["date"], errors="raise")
    if df["date"].duplicated().any():
        raise ValueError(f"Duplicate dates in {source}")

    numeric = (
        "lon_360", "lon_180", "lat", "area_km2", "pwp_cell_count",
        "valid_ocean_cell_count", "mask_cell_count", "ocean_data_coverage_pct",
        "mean_pwp_sst_c", "max_pwp_sst_c", "area_weighted_sst_std_c",
        "threshold_c", "centroid_resultant_length", "centroid_angular_dispersion_deg",
    )
    for col in numeric:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df["threshold_fallback_used"] = parse_bool_series(df["threshold_fallback_used"])
    if not np.allclose(df["threshold_c"].dropna().to_numpy(float), threshold_c):
        raise ValueError(f"threshold_c mismatch in {source}")

    flag = df["quality_flag"].astype(str).str.upper()
    no_pwp = flag.str.contains("NO_PWP_CELLS", regex=False, na=False)
    valid = (
        np.isfinite(df["area_km2"].to_numpy(float))
        & np.isfinite(df["lon_360"].to_numpy(float))
        & np.isfinite(df["lat"].to_numpy(float))
        & np.isfinite(df["ocean_data_coverage_pct"].to_numpy(float))
        & (df["ocean_data_coverage_pct"].to_numpy(float) >= FINAL_MINIMUM_COVERAGE_PCT)
        & ~df["threshold_fallback_used"].to_numpy(bool)
        & ~no_pwp.to_numpy(bool)
    )

    rejected = int((~valid).sum())
    df = df.loc[valid].copy().sort_values("date").reset_index(drop=True)
    if df.empty:
        raise ValueError(f"No valid rows remain for {threshold_c:.1f} °C")

    df["lon_unwrapped_deg"] = unwrap_longitude_deg(df["lon_360"].to_numpy(float))
    ref_lon, ref_lat, ref_r = spherical_reference_centroid(df["lon_360"], df["lat"])
    df["reference_lon_360"] = ref_lon
    df["reference_lat"] = ref_lat
    df["reference_resultant_length"] = ref_r
    df["radial_excursion_km"] = great_circle_distance_km(df["lon_360"], df["lat"], ref_lon, ref_lat)

    df.attrs["rejected_rows"] = rejected
    df.attrs["reference_lon_360"] = ref_lon
    df.attrs["reference_lat"] = ref_lat
    df.attrs["reference_resultant_length"] = ref_r
    return df


def load_all_thresholds():
    series = {t: load_threshold_series(t, INPUT_FILES[t]) for t in THRESHOLDS_C}
    common = set(series[28.0]["date"])
    for t in THRESHOLDS_C[1:]:
        common &= set(series[t]["date"])
    common = pd.DatetimeIndex(sorted(common))
    if common.empty:
        raise ValueError("No common dates across thresholds after QC.")
    for t in THRESHOLDS_C:
        series[t] = series[t].loc[series[t]["date"].isin(common)].copy().sort_values("date").reset_index(drop=True)
        if len(series[t]) != len(common):
            raise ValueError("Common-date alignment failure.")
    return series


# =============================================================================
# SUMMARY METRICS
# =============================================================================

def summarize_threshold(t, df):
    area = df["area_km2"].to_numpy(float)
    lon = df["lon_unwrapped_deg"].to_numpy(float)
    lat = df["lat"].to_numpy(float)
    radial = df["radial_excursion_km"].to_numpy(float)

    area_mean = fmean(area)
    area_std = fstd(area)
    lon_p05, lon_p25, lon_p50, lon_p75, lon_p95 = [fq(lon, q) for q in (0.05, 0.25, 0.50, 0.75, 0.95)]
    lat_p05, lat_p25, lat_p50, lat_p75, lat_p95 = [fq(lat, q) for q in (0.05, 0.25, 0.50, 0.75, 0.95)]
    area_p05, area_p25, area_p50, area_p75, area_p95 = [fq(area, q) for q in (0.05, 0.25, 0.50, 0.75, 0.95)]

    return {
        "threshold_c": t,
        "n_days": len(df),
        "start_date": df["date"].min(),
        "end_date": df["date"].max(),
        "reference_lon_360": float(df["reference_lon_360"].iloc[0]),
        "reference_lat": float(df["reference_lat"].iloc[0]),
        "reference_resultant_length": float(df["reference_resultant_length"].iloc[0]),
        "mean_area_km2": area_mean,
        "mean_area_million_km2": area_mean / 1e6,
        "median_area_km2": area_p50,
        "median_area_million_km2": area_p50 / 1e6,
        "std_area_km2": area_std,
        "cv_area_pct": 100.0 * area_std / area_mean,
        "area_p05_km2": area_p05,
        "area_p95_km2": area_p95,
        "area_iqr_km2": area_p75 - area_p25,
        "area_p95_p05_km2": area_p95 - area_p05,
        "longitude_mean_deg": fmean(lon),
        "longitude_median_deg": lon_p50,
        "longitude_std_deg": fstd(lon),
        "longitude_p05_deg": lon_p05,
        "longitude_p95_deg": lon_p95,
        "longitude_iqr_deg": lon_p75 - lon_p25,
        "longitude_robust_amplitude_deg": lon_p95 - lon_p05,
        "longitude_full_range_deg": float(np.nanmax(lon) - np.nanmin(lon)),
        "latitude_mean_deg": fmean(lat),
        "latitude_median_deg": lat_p50,
        "latitude_std_deg": fstd(lat),
        "latitude_p05_deg": lat_p05,
        "latitude_p95_deg": lat_p95,
        "latitude_iqr_deg": lat_p75 - lat_p25,
        "latitude_robust_amplitude_deg": lat_p95 - lat_p05,
        "latitude_full_range_deg": float(np.nanmax(lat) - np.nanmin(lat)),
        "radial_excursion_mean_km": fmean(radial),
        "radial_excursion_median_km": fmedian(radial),
        "radial_excursion_p05_km": fq(radial, 0.05),
        "radial_excursion_p95_km": fq(radial, 0.95),
        "radial_excursion_max_km": float(np.nanmax(radial)),
    }


def build_threshold_summary(series):
    out = pd.DataFrame([summarize_threshold(t, series[t]) for t in THRESHOLDS_C]).sort_values("threshold_c").reset_index(drop=True)
    primary = out.loc[np.isclose(out["threshold_c"], PRIMARY_THRESHOLD_C)].iloc[0]
    metrics = {
        "mean_area_million_km2": "mean_area",
        "longitude_std_deg": "longitude_std",
        "longitude_robust_amplitude_deg": "longitude_robust_amplitude",
        "latitude_std_deg": "latitude_std",
        "latitude_robust_amplitude_deg": "latitude_robust_amplitude",
        "radial_excursion_p95_km": "radial_excursion_p95",
    }
    for col, name in metrics.items():
        denom = float(primary[col])
        out[f"{name}_ratio_vs_28C"] = out[col] / denom
        out[f"{name}_pct_change_vs_28C"] = 100.0 * (out[col] / denom - 1.0)
    return out


# =============================================================================
# DAILY WIDE / PAIRWISE SEPARATION
# =============================================================================

def build_daily_wide(series):
    out = None
    for t in THRESHOLDS_C:
        tag = threshold_tag(t)
        df = series[t]
        cur = pd.DataFrame({
            "date": df["date"],
            f"area_km2_{tag}": df["area_km2"].to_numpy(float),
            f"lon_360_{tag}": df["lon_360"].to_numpy(float),
            f"lon_unwrapped_deg_{tag}": df["lon_unwrapped_deg"].to_numpy(float),
            f"lat_{tag}": df["lat"].to_numpy(float),
            f"radial_excursion_km_{tag}": df["radial_excursion_km"].to_numpy(float),
        })
        out = cur if out is None else out.merge(cur, on="date", how="inner", validate="one_to_one")

    for t1, t2 in ((28.0, 28.5), (28.0, 29.0), (28.5, 29.0)):
        a, b = threshold_tag(t1), threshold_tag(t2)
        pair = f"{a}_vs_{b}"
        out[f"delta_lon_deg_{pair}"] = wrap_delta_longitude_deg(out[f"lon_360_{b}"] - out[f"lon_360_{a}"])
        out[f"delta_lat_deg_{pair}"] = out[f"lat_{b}"] - out[f"lat_{a}"]
        out[f"centroid_separation_km_{pair}"] = great_circle_distance_km(out[f"lon_360_{a}"], out[f"lat_{a}"], out[f"lon_360_{b}"], out[f"lat_{b}"])
        out[f"area_ratio_{b}_to_{a}"] = out[f"area_km2_{b}"] / out[f"area_km2_{a}"]

    return out.sort_values("date").reset_index(drop=True)


def summarize_pairwise(daily):
    rows = []
    for t1, t2 in ((28.0, 28.5), (28.0, 29.0), (28.5, 29.0)):
        a, b = threshold_tag(t1), threshold_tag(t2)
        pair = f"{a}_vs_{b}"
        d = daily[f"centroid_separation_km_{pair}"].to_numpy(float)
        dlon = daily[f"delta_lon_deg_{pair}"].to_numpy(float)
        dlat = daily[f"delta_lat_deg_{pair}"].to_numpy(float)
        ratio = daily[f"area_ratio_{b}_to_{a}"].to_numpy(float)
        rows.append({
            "threshold_1_c": t1,
            "threshold_2_c": t2,
            "pair": f"{t1:.1f} vs {t2:.1f} °C",
            "n_days": len(daily),
            "mean_separation_km": fmean(d),
            "median_separation_km": fmedian(d),
            "separation_p05_km": fq(d, 0.05),
            "separation_p95_km": fq(d, 0.95),
            "maximum_separation_km": float(np.nanmax(d)),
            "mean_signed_delta_lon_deg_t2_minus_t1": fmean(dlon),
            "median_signed_delta_lon_deg_t2_minus_t1": fmedian(dlon),
            "delta_lon_p05_deg": fq(dlon, 0.05),
            "delta_lon_p95_deg": fq(dlon, 0.95),
            "mean_signed_delta_lat_deg_t2_minus_t1": fmean(dlat),
            "median_signed_delta_lat_deg_t2_minus_t1": fmedian(dlat),
            "delta_lat_p05_deg": fq(dlat, 0.05),
            "delta_lat_p95_deg": fq(dlat, 0.95),
            "mean_area_ratio_t2_to_t1": fmean(ratio),
            "median_area_ratio_t2_to_t1": fmedian(ratio),
        })
    return pd.DataFrame(rows)


# =============================================================================
# DECISION REGISTRY
# =============================================================================

def strictly_decreasing(x):
    return bool(np.all(np.diff(np.asarray(x, dtype=float)) < 0.0))


def strictly_increasing(x):
    return bool(np.all(np.diff(np.asarray(x, dtype=float)) > 0.0))


def build_decision_registry(summary, pairwise):
    s = summary.sort_values("threshold_c")
    area_down = strictly_decreasing(s["mean_area_km2"])
    lon_amp_up = strictly_increasing(s["longitude_robust_amplitude_deg"])
    lon_std_up = strictly_increasing(s["longitude_std_deg"])
    radial_up = strictly_increasing(s["radial_excursion_p95_km"])
    all_sep = bool(np.all(pairwise["median_separation_km"].to_numpy(float) > 0.0))

    if area_down and lon_amp_up and radial_up:
        status = "SUPPORTED_BY_ROBUST_LONGITUDINAL_AND_RADIAL_METRICS"
        text = (
            "As the threshold-defined domain becomes smaller, both robust longitudinal amplitude "
            "and P95 radial centroid excursion increase monotonically. This supports the geometric-"
            "sensitivity hypothesis."
        )
    elif area_down and (lon_amp_up or lon_std_up or radial_up):
        status = "PARTIALLY_SUPPORTED"
        text = (
            "Domain area decreases monotonically with threshold, while only some centroid-amplitude "
            "metrics increase monotonically. Geometric sensitivity therefore depends on more than "
            "total area alone."
        )
    else:
        status = "NOT_MONOTONICALLY_SUPPORTED"
        text = (
            "The three thresholds do not show a simple monotonic inverse domain-size/centroid-amplitude "
            "ordering. Geometry, connectivity, asymmetry and the location of boundary changes must be "
            "considered."
        )

    return {
        "mean_area_strictly_decreases_28_to_29": area_down,
        "longitude_robust_amplitude_strictly_increases_28_to_29": lon_amp_up,
        "longitude_std_strictly_increases_28_to_29": lon_std_up,
        "radial_p95_strictly_increases_28_to_29": radial_up,
        "all_pairwise_median_centroid_separations_positive": all_sep,
        "geometric_sensitivity_status": status,
        "geometric_sensitivity_interpretation": text,
    }


# =============================================================================
# OUTPUTS
# =============================================================================

def export_tables(summary, pairwise, daily):
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    s = summary.copy()
    for col in ("start_date", "end_date"):
        s[col] = pd.to_datetime(s[col]).dt.strftime("%Y-%m-%d")
    d = daily.copy()
    d["date"] = pd.to_datetime(d["date"]).dt.strftime("%Y-%m-%d")
    s.to_csv(SUMMARY_FILE, index=False, float_format="%.10g")
    pairwise.to_csv(PAIRWISE_FILE, index=False, float_format="%.10g")
    d.to_csv(DAILY_FILE, index=False, float_format="%.10g")
    return SUMMARY_FILE, PAIRWISE_FILE, DAILY_FILE


def plot_summary(summary):
    s = summary.sort_values("threshold_c")
    labels = [f"{t:.1f} °C" for t in s["threshold_c"]]
    fig, axes = plt.subplots(1, 3, figsize=(15.0, 5.2), constrained_layout=True)

    axes[0].bar(labels, s["mean_area_million_km2"])
    axes[0].set_ylabel("Mean PWP area (10⁶ km²)")
    axes[0].set_xlabel("SST threshold")
    axes[0].grid(axis="y", linestyle=GRID_LINESTYLE, linewidth=GRID_LINEWIDTH, alpha=GRID_ALPHA)
    add_panel_label(axes[0], "A)")

    axes[1].bar(labels, s["longitude_robust_amplitude_deg"])
    axes[1].set_ylabel("Longitude P95−P05 amplitude (°)")
    axes[1].set_xlabel("SST threshold")
    axes[1].grid(axis="y", linestyle=GRID_LINESTYLE, linewidth=GRID_LINEWIDTH, alpha=GRID_ALPHA)
    add_panel_label(axes[1], "B)")

    axes[2].bar(labels, s["radial_excursion_p95_km"])
    axes[2].set_ylabel("P95 radial centroid excursion (km)")
    axes[2].set_xlabel("SST threshold")
    axes[2].grid(axis="y", linestyle=GRID_LINESTYLE, linewidth=GRID_LINEWIDTH, alpha=GRID_ALPHA)
    add_panel_label(axes[2], "C)")

    fig.suptitle("PWP thermal-domain size and centroid-displacement sensitivity", fontsize=14)
    return save_figure(fig, "pwp_domain_size_centroid_sensitivity_summary")


def plot_pairwise_timeseries(daily):
    specs = ((28.0, 28.5), (28.0, 29.0), (28.5, 29.0))
    fig, axes = plt.subplots(3, 1, figsize=(14.5, 9.5), sharex=True, constrained_layout=True)

    for i, (ax, (t1, t2)) in enumerate(zip(axes, specs)):
        a, b = threshold_tag(t1), threshold_tag(t2)
        pair = f"{a}_vs_{b}"
        ax.plot(daily["date"], daily[f"centroid_separation_km_{pair}"], linewidth=0.75, label=f"{t1:.1f} vs {t2:.1f} °C")
        ax.set_ylabel("Centroid\nseparation (km)")
        ax.legend(frameon=False, loc="upper right")
        ax.grid(linestyle=GRID_LINESTYLE, linewidth=GRID_LINEWIDTH, alpha=GRID_ALPHA)
        add_panel_label(ax, f"{chr(65+i)})")

    min_date = pd.Timestamp(daily["date"].min())
    max_date = pd.Timestamp(daily["date"].max())
    years = np.arange(YEAR_TICK_ANCHOR, max_date.year + YEAR_TICK_INTERVAL, YEAR_TICK_INTERVAL)
    ticks = pd.DatetimeIndex(pd.to_datetime([f"{y}-01-01" for y in years]))
    inside = (ticks >= min_date) & (ticks <= max_date)
    axes[-1].set_xlim(min_date, max_date)
    axes[-1].set_xticks(ticks[inside])
    axes[-1].set_xticklabels([str(y) for y in years[inside]])
    axes[-1].set_xlabel("Year")
    for ax in axes[:-1]:
        ax.tick_params(axis="x", labelbottom=False)

    fig.suptitle("Geographical separation of simultaneous PWP centroids across SST thresholds", fontsize=14)
    return save_figure(fig, "pwp_interthreshold_centroid_separation_timeseries")


def serializable(value: Any):
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value) if np.isfinite(value) else None
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    if pd.isna(value):
        return None
    return value


def records(data):
    return [{k: serializable(v) for k, v in row.items()} for row in data.to_dict(orient="records")]


def write_reports(summary, pairwise, decision, series, created_files):
    generated = datetime.now(timezone.utc).isoformat()
    lines = [
        PROGRAM_NAME,
        "=" * 78,
        "",
        "1. PROGRAM",
        "-" * 78,
        f"Version                         : {PROGRAM_VERSION}",
        f"Generated UTC                   : {generated}",
        f"Project root                    : {PROJECT_DIR}",
        "",
        "2. SCIENTIFIC PURPOSE",
        "-" * 78,
        "Quantify threshold-defined PWP domain size, centroid displacement amplitude,",
        "and simultaneous geographical separation among the 28, 28.5 and 29 °C centroids.",
        "",
        "3. INTERPRETATION BOUNDARY",
        "-" * 78,
        "This program quantifies GEOMETRIC / STATISTICAL centroid sensitivity.",
        "It does not demonstrate ocean-dynamical inertia or forcing strength.",
        "",
        "4. INPUT / QC",
        "-" * 78,
        "Upstream program                 : Program 05",
        "Final operational coverage       : >= 98.0%",
        "Original LOW_COVERAGE string     : not an automatic rejection",
        "",
        "5. THRESHOLD METRICS",
        "-" * 78,
    ]

    for row in summary.itertuples(index=False):
        lines.append(
            f"{row.threshold_c:.1f} °C | mean area={row.mean_area_million_km2:.3f} ×10⁶ km² | "
            f"lon SD={row.longitude_std_deg:.3f}° | lon P95-P05={row.longitude_robust_amplitude_deg:.3f}° | "
            f"lat P95-P05={row.latitude_robust_amplitude_deg:.3f}° | radial P95={row.radial_excursion_p95_km:.1f} km"
        )
        lines.append(f"         reference centroid=({row.reference_lon_360:.3f}°E, {row.reference_lat:+.3f}°)")

    lines += ["", "6. INTER-THRESHOLD CENTROID SEPARATION", "-" * 78]
    for row in pairwise.itertuples(index=False):
        lines.append(
            f"{row.pair:<18s} | median={row.median_separation_km:.1f} km | P05={row.separation_p05_km:.1f} km | "
            f"P95={row.separation_p95_km:.1f} km | max={row.maximum_separation_km:.1f} km | "
            f"median Δlon={row.median_signed_delta_lon_deg_t2_minus_t1:+.2f}° | "
            f"median Δlat={row.median_signed_delta_lat_deg_t2_minus_t1:+.2f}°"
        )

    lines += ["", "7. DECISION REGISTRY", "-" * 78]
    for k, v in decision.items():
        if k != "geometric_sensitivity_interpretation":
            lines.append(f"{k:<58s}: {v}")

    lines += [
        "",
        "8. SCIENTIFIC INTERPRETATION",
        "-" * 78,
        decision["geometric_sensitivity_interpretation"],
        "",
        "The three centroids are distinct geographical observables, not interchangeable",
        "estimates of one true point. Absolute centroid amplitude and wavelet power must",
        "therefore not be compared across thresholds as if geometric sensitivity were identical.",
        "",
        "The threshold paper should distinguish:",
        "    1. mean centroid position,",
        "    2. amplitude of centroid displacement,",
        "    3. temporal organization of displacement.",
        "",
        "Program 31 and Program 34 quantify threshold-sensitive geometry; Program 32",
        "quantifies the much more threshold-robust timing of interannual variance.",
        "",
        "9. FILES CREATED",
        "-" * 78,
    ]
    lines.extend(str(p) for p in created_files)
    lines += [
        "",
        "10. FINAL STATUS",
        "-" * 78,
        "Machine status                   : PASS",
        "Paper-1 diagnostic status        : READY FOR SCIENTIFIC INTERPRETATION",
        "",
        "=" * 78,
    ]

    REPORT_TXT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    payload = {
        "program": PROGRAM_NAME,
        "version": PROGRAM_VERSION,
        "generated_utc": generated,
        "project_root": str(PROJECT_DIR),
        "thresholds_c": list(THRESHOLDS_C),
        "primary_threshold_c": PRIMARY_THRESHOLD_C,
        "final_minimum_coverage_pct": FINAL_MINIMUM_COVERAGE_PCT,
        "threshold_summary": records(summary),
        "pairwise_centroid_separation": records(pairwise),
        "decision_registry": {k: serializable(v) for k, v in decision.items()},
        "scientific_safeguards": [
            "Geometric sensitivity is not equivalent to dynamical inertia.",
            "Area alone is not assumed to control centroid sensitivity.",
            "Different thresholds define different geographical observables.",
            "Absolute displacement amplitude does not directly measure ENSO forcing strength.",
            "Program 32, not Program 34, provides the cross-threshold timing robustness result.",
        ],
        "files_created": [str(p) for p in created_files],
    }
    REPORT_JSON.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return REPORT_TXT, REPORT_JSON


# =============================================================================
# MAIN
# =============================================================================

def main():
    rule()
    print(PROGRAM_NAME)
    rule()

    section("## CONFIGURATION")
    item("Program version", PROGRAM_VERSION)
    item("Project root", PROJECT_ROOT)
    item("Thresholds", "28.0, 28.5, 29.0 °C")
    item("Primary threshold", "28.0 °C")
    item("Upstream centroid program", "Program 05")
    item("Final minimum coverage", f"{FINAL_MINIMUM_COVERAGE_PCT:.1f}%")
    item("Original LOW_COVERAGE string", "not an automatic Program-34 rejection")
    item("Earth radius", f"{EARTH_RADIUS_KM:.4f} km")
    item("Threshold-level p-value", "NOT CALCULATED (only 3 thresholds)")

    validate_configuration()

    section("## LOADING AUTHORITATIVE PROGRAM-05 SERIES")
    series = load_all_thresholds()
    for t in THRESHOLDS_C:
        df = series[t]
        item(f"{t:.1f} °C", f"{len(df):,} common valid dates | {df['date'].min():%Y-%m-%d} to {df['date'].max():%Y-%m-%d}")
        item(f"{t:.1f} °C source", INPUT_FILES[t])

    section("## THRESHOLD-SPECIFIC DOMAIN / CENTROID METRICS")
    summary = build_threshold_summary(series)
    for row in summary.itertuples(index=False):
        print(
            f"{row.threshold_c:.1f} °C | mean area={row.mean_area_million_km2:7.3f} ×10⁶ km² | "
            f"lon SD={row.longitude_std_deg:6.3f}° | lon P95-P05={row.longitude_robust_amplitude_deg:6.3f}° | "
            f"radial P95={row.radial_excursion_p95_km:7.1f} km"
        )

    section("## BUILDING ALIGNED DAILY DIAGNOSTICS")
    daily = build_daily_wide(series)
    item("Aligned common dates", f"{len(daily):,}")

    section("## INTER-THRESHOLD CENTROID SEPARATION")
    pairwise = summarize_pairwise(daily)
    for row in pairwise.itertuples(index=False):
        print(
            f"{row.pair:<18s} | median={row.median_separation_km:7.1f} km | "
            f"P95={row.separation_p95_km:7.1f} km | max={row.maximum_separation_km:7.1f} km | "
            f"median Δlon={row.median_signed_delta_lon_deg_t2_minus_t1:+6.2f}° | "
            f"median Δlat={row.median_signed_delta_lat_deg_t2_minus_t1:+6.2f}°"
        )

    section("## GEOMETRIC-SENSITIVITY DECISION")
    decision = build_decision_registry(summary, pairwise)
    for k, v in decision.items():
        if k != "geometric_sensitivity_interpretation":
            item(k, v)
    print()
    print(decision["geometric_sensitivity_interpretation"])

    section("## PUBLICATION SPATIAL-DISTRIBUTION SUMMARY")
    spatial_summary = build_spatial_distribution_summary(series)
    for row in spatial_summary.itertuples(index=False):
        print(
            f"{row.threshold_c:.1f} °C | N={row.n_days:,} | "
            f"mean spherical centroid=({row.mean_spherical_lon_360_deg:.3f}°E, "
            f"{row.mean_spherical_lat_deg:+.3f}°) | "
            f"mean area={row.mean_daily_pwp_area_million_km2:.3f} ×10⁶ km²"
        )

    section("## EXPORTING TABLES")
    created = list(export_tables(summary, pairwise, daily))

    spatial_summary_path = export_spatial_distribution_summary(spatial_summary)
    separation_timeseries_path = export_interthreshold_separation_timeseries(daily)

    created.extend(
        [
            spatial_summary_path,
            separation_timeseries_path,
        ]
    )

    for p in created:
        print(p)

    section("## GENERATING FIGURES")
    for group in (
        plot_summary(summary),
        plot_pairwise_timeseries(daily),
        plot_centroid_spatial_distribution(series, spatial_summary),
    ):
        created.extend(group)
        for p in group:
            print(p)

    section("## WRITING REPORTS")
    txt, js = write_reports(summary, pairwise, decision, series, created)
    print(txt)
    print(js)

    print()
    rule()
    print("PROGRAM 34 COMPLETED SUCCESSFULLY.")
    print()
    print("Domain size, centroid displacement amplitude, simultaneous inter-threshold separation, and full-record centroid spatial distributions were quantified.")
    print("Interpret the result as geometric/statistical centroid sensitivity, not direct evidence of ocean-dynamical inertia.")
    print()
    print("After scientific interpretation, the threshold-definition paper is ready for SCIENCE FREEZE and dedicated article handover.")
    rule()


if __name__ == "__main__":
    main()
