# -*- coding: utf-8 -*-
"""Shared infrastructure for the PWP Scientific Analysis Platform."""

from .reporting import (
    DEFAULT_KEY_WIDTH,
    DEFAULT_WIDTH,
    ConsoleReport,
    MessageLevel,
    TextReport,
    banner,
    failure,
    item,
    progress,
    render_banner,
    render_key_value,
    render_rule,
    render_section,
    render_status,
    rule,
    section,
    success,
    warning,
)
from .version import (
    CORE_VERSION,
    PLATFORM_NAME,
    PLATFORM_VERSION,
    VersionInfo,
    version_string,
)

__all__ = [
    "CORE_VERSION",
    "PLATFORM_NAME",
    "PLATFORM_VERSION",
    "VersionInfo",
    "version_string",
    "DEFAULT_KEY_WIDTH",
    "DEFAULT_WIDTH",
    "ConsoleReport",
    "MessageLevel",
    "TextReport",
    "banner",
    "failure",
    "item",
    "progress",
    "render_banner",
    "render_key_value",
    "render_rule",
    "render_section",
    "render_status",
    "rule",
    "section",
    "success",
    "warning",
]
